[package]
name = "lastf"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "lf"
path = "src/main.rs"

[dependencies]
clap = { version = "3.0.0-rc.7", features = ["cargo"] }
ignore = "0.4.18"
wild = "2.0.4"
