[package]
name = "lastf"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "lf"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.2"
walkdir = "2.3.2"

[build-dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
